### ISSUE TITLE
please add some credits

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [gmarull/qtmodern#11]
Hi man,
just found your work and wondering, that the ui and stylesheets and the way of assign frameless window is really the same I did on my Qt C++ version:
https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle

would be nice, if you add some credits for my base work.

PS: nice python port by the way!

cheers and thx,
Jorgen

**Comment by Jorgen-VikingGod** [comment]
sorry - just saw that you already added it in your readme.md file

**Comment by gmarull** [comment]
If you want me to increase visibility of credits let me know ;-)

**Comment by Jorgen-VikingGod** [comment]
thx. Everything is fine for me. Did not see the link in the readme before ;)
