### ISSUE TITLE
Possible import issue.

### ISSUE THREAD

**Issue by grant-zietsman** [gmarull/qtmodern#13]
I noticed the following error when trying to use qtmodern after installing with pip.

```sh
AttributeError: module 'qtmodern' has no attribute 'styles'
```

The code that generated this error is.

```py
import qtmodern
qtmodern.styles.dark(app)
```

It seems that the [qtmodern/\_\_init\_\_.py](https://github.com/gmarull/qtmodern/blob/master/qtmodern/__init__.py) file does not export styles. I would have expected something along these lines.

```py
__version__ = '0.1.4'
""" str: Package version. """
from .styles import dark
```

I just realised, while writing this, that I can resolve the import as follows.

```py
import qtmodern.styles
qtmodern.styles.dark(app)
```

If you don't want to update code, perhaps you can add `import qtmoderm.styles` to the code block in the readme as it isn't totally obvious.

### Importing with PySide2

On a side note, for those using PySide2, you will probably get this warning.

```sh
RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyside2"
  'using "{}"'.format(initial_api, API), RuntimeWarning)
```

In which case, the snippet below may prove useful.

```py
try:
    import warnings
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        import qtmodern.styles
except ImportError:
    pass
else:
    qtmodern.styles.dark(app)
```

**Comment by gmarull** [comment]
The styles subpackage is intended to be imported explicitely, as it is shown on the examples. I'll update the readme though, as it's true that it may be unclear.

Regarding the PySide2 warning, it's something out of our control as it depends on `qtpy`. You can also skip it by setting the `QT_API` env var.
