### ISSUE TITLE
Default title

### ISSUE THREAD

**Issue by mgrady3** [gmarull/qtmodern#2]
When you wrap a widget with a title (QMainWindow for instance) with the qtmodern.windows.ModernWindow widget, you lose the title from the wrapped widget and instead the ModernWindow just shows a default title "Title".

It would be nice if the ModernWindow widget could check if the widget it is wrapping has a title set, and if so, automatically set the ModernWindow title to that value.

**Comment by elizabwth** [comment]
Does calling [setTitle](https://github.com/gmarull/qtmodern/blob/682ae09b3b3880c998fa51dd1e91fb2c400cd1c9/qtmodern/windows.py#L134) on that widget work?

**Comment by mgrady3** [comment]
If the widget you are referring to is the ModernWindow widget, then yes, the setTitle() method works correctly to set the title of the wrapper window.

My suggestion would be to add a few lines of code to the ModernWindow widget's init method:

The init method takes w as an argument, which is the widget to be wrapped. The QWidget base class exposes a property called windowTitle. So the init method of ModernWindow could check the value of w.windowTitle, if its not Null and is a valid String or QString then simply call self.setTitle(w.windowTitle)

**Comment by elizabwth** [comment]
Great suggestion. A pull request would probably be the best solution here.

**Comment by gmarull** [comment]
Hi, clearly this is something that needs to be fixed. I’ll take a look to your PR later. Also, the geometry should probably be kept too (now it defaults to 1024x768, something I randomly decided...)

**Comment by mgrady3** [comment]
The geometry should be a quick fix as well to just add a bit of code to ModernWindow.__init__() or setupUI().

**Comment by gmarull** [comment]
Hi all,

I have fixed this issue in this commit https://github.com/gmarull/qtmodern/commit/a7ff8c24ba3337ae6c4118891eae94c4eff112b3 and released 0.1.1.

@mgrady3 I have not taken your PR, as I also added the geometry fix. However you're credited on the commit message ;)

Thanks!
