### ISSUE TITLE
Include license file in sdist

### ISSUE THREAD

**Issue by hmaarrfk** [gmarull/qtmodern#31]
It would be nice if you included in the source distribution.

Add a file call: `MANIFEST.in`
with
```
include LICENSE
```

(And maybe create a new release)
thx

**Comment by Jerakin** [comment]
Why do you think this is needed? A reference to that it is under `MIT License` should already be in the package metadata, it gets added automatically when uploading to pypi.

**Comment by hmaarrfk** [comment]
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

The easiest way to do this is to ship the plain text file.

It helps downstream packagers adhere to your wishes.

> , it gets added automatically when uploading to pypi

I don't think so
![image](https://user-images.githubusercontent.com/90008/71677031-b0cb4800-2d4f-11ea-85f0-94c067d1e5fc.png)
