### ISSUE TITLE
new release for light mode

### ISSUE THREAD

**Issue by hmaarrfk** [gmarull/qtmodern#32]
Light mode looks pretty cool. Would be nice to have it available on pypi (then I can package it for conda-forge ;))

**Comment by Axel-Erfurt** [comment]
how to use _light_ ?

`qtmodern.styles.light(app)`

does not work.

> 'qtmodern.styles' has no attribute 'light'

**Comment by Jerakin** [comment]
@Axel-Erfurt Have you installed qtmodern with `pip`? If that's the case then it will not work because it is not yet released. You can install the latest master with `pip` like this `pip install https://github.com/gmarull/qtmodern/archive/master.zip`

**Comment by Axel-Erfurt** [comment]
Thanks!

**Comment by Jerakin** [comment]
[qtmodern 0.2.0](https://github.com/gmarull/qtmodern/releases/tag/0.2.0) with the light theme have been released
