### ISSUE TITLE
pyinstaller lost file

### ISSUE THREAD

**Issue by tiantian1645** [gmarull/qtmodern#34]
Hello:
    When i try to pack the script by pyinstaller i get 
```
2019-12-10 10:29:35.378 | ERROR    | __main__:<module>:2128 - exception in main loop
File qt_frame.py, line 2120, in <module>

File qt_frame.py, line 156, in __init__

File qt_frame.py, line 217, in initUI

File qt_frame.py, line 829, in createMotor

File qt_modern_dialog.py, line 199, in __init__

File qt_modern_dialog.py, line 143, in setupUi

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\qt_test\\dist\\projectname\\qtmodern\\resources/frameless.qss'
```
and if ound add these two line in .spec file could fix
```
a.datas += [('.\\qtmodern\\resources\\frameless.qss', 'C:\\Users\\Administrator\\qt_test\\venv\\Lib\\site-packages\\qtmodern\\resources\\frameless.qss', 'DATA')]
a.datas += [('.\\qtmodern\\resources\\style.qss', 'C:\\Users\\Administrator\\qt_test\\venv\\Lib\\site-packages\\qtmodern\\resources\\style.qss', 'DATA')]
```

**Comment by Jerakin** [comment]
This is not a qtmodern error but how Pyinstaller and python works. Here is how to fix it.

First in your `.spec` file you need to include the datas (which it looks like you are doing, but not in a very good way)
```python
import importlib

package_imports = [['qtmodern', ['resources/frameless.qss', 'resources/style.qss']]]

added_file = []
for package, files in package_imports:
    proot = Path(importlib.import_module(package).__file__).parent
    added_file.extend((proot / f, package) for f in files)

Analysis(['project/__main__.py'],
             datas=added_file
)

```

Secondly you need to tell your python application to change the paths if the application is built, so in your bootstrap (first file that runs) add this after importing.

```
import qtmodern.windows
import qtmodern.styles

root = Path()
if getattr(sys, 'frozen', False):
    root = Path(sys._MEIPASS)
    qtmodern.styles._STYLESHEET = root / 'qtmodern/style.qss'
    qtmodern.windows._FL_STYLESHEET = root / 'qtmodern/frameless.qss'
```

**Comment by NetinhoDaCosta** [comment]
That part with the "import importlib etc... "
Do you add that in the .spec file?
Looks like python code

I did add the bottom part in the main python code of my application. 
Only attempting to figure out how to use that top part.

**Comment by bactone** [comment]
> Path()

while which module does Path() belongs to be?

**Comment by bactone** [comment]
> import qtmodern.windows
> import qtmodern.styles
> 
> root = Path()
> if getattr(sys, 'frozen', False):
>     root = Path(sys._MEIPASS)
>     qtmodern.styles._STYLESHEET = root / 'qtmodern/style.qss'
>     qtmodern.windows._FL_STYLESHEET = root / 'qtmodern/frameless.qss'

which module does Path() belongs to be? thanks @Jerakin

**Comment by Jerakin** [comment]
The builtin [pathlib](https://docs.python.org/3/library/pathlib.html) added in python 3.4

**Comment by bactone** [comment]
> The builtin [pathlib](https://docs.python.org/3/library/pathlib.html) added in python 3.4

thanks, it saves me.
