### ISSUE TITLE
pyinstaller is not taking the styling into account

### ISSUE THREAD

**Issue by NetinhoDaCosta** [gmarull/qtmodern#59]
When using pyinstaller, the .exe file gives an error complaining about missing qtmodern files.
using pyinstaller v4.0
Python v 3.7.3
on windows 10

Traceback (most recent call last):
  File "my_filename.py", line 262, in <module>
  File "qtmodern\styles.py", line 70, in dark
  File "qtmodern\styles.py", line 23, in _apply_base_theme
FileNotFoundError: [Errno 2] No such file or directory: " 'C:\\sers\\MyName\\AppData\\Local\\Temp\\_MEI166802\\qtmodern\\resources/styles.qss'
[36020] failed to execute script my_filename

**Comment by Jerakin** [comment]
Hi! Please check this issue out. :)

https://github.com/gmarull/qtmodern/issues/34#issuecomment-564061097

**Comment by NetinhoDaCosta** [comment]
Ah thanks for pointing that out Jerakin, I was searching for hours.
I did add the data file exactly as tiantian1645 but that failed for me too. Now I know why.
I'll attempt to understand that solution now : )  (figure out what goes in what file exactly)
