### ISSUE TITLE
Font size adjustment is not supported

### ISSUE THREAD

**Issue by SteveDoyle2** [gmarull/qtmodern#6]
The default font size is 8.  At a later point in the code, I have an option to resize the font.  The current style overwrites the desired font size for the current window as:

        font = QFont()
        font.setPointSize(font_size)
        self.setFont(font)

I've manage to trace the problem to the following section (in styles.py):

    with open(_STYLESHEET) as stylesheet:
        app.setStyleSheet(stylesheet.read())

The following block of code, while it does set the font, it does not prevent resizing from working.

    font = app.font()
    font.setPointSize(font.pointSize() + 2)
    app.setFont(font)

**Comment by gmarull** [comment]
Hi Steve,

Certainly it should inherit from the contained window. Feel free to make a PR, otherwise I will fix it this week when I got a chance.

-Gerard
