### ISSUE TITLE
I have ported it to PySide6. 

### ISSUE THREAD

**Issue by blackball** [gmarull/qtmodern#63]
Hi,  

I have ported this small but nice lib to PySide6. If you would like to have a try it's here: 

https://github.com/blackball/qtmodern

FYI

**Comment by Jerakin** [comment]
That's convinient if you want to use PySide6 right now :)

Note that this library is using QtPy which currently does not support PySide6 but as soon as it does so will qtmodern. Here is the issue for PySide6 in QtPy https://github.com/spyder-ide/qtpy/issues/229
