### ISSUE TITLE
Example to set theme during runtime.

### ISSUE THREAD

**Issue by wxguy** [gmarull/qtmodern#65]
Thanks for the theme. It works perfectly on my system. Now I would like to implement dark and light theme to my application with switch to change from a click of button. How do I do that?

**Comment by Jerakin** [comment]
Sorry for a late reply. This is actually already in the example :)

Change theme
https://github.com/gmarull/qtmodern/blob/7a9aeb1a4f77cf002e53910cfe724f3808496733/examples/mainwindow.py#L61-L66

Connect buttons as usual
https://github.com/gmarull/qtmodern/blob/7a9aeb1a4f77cf002e53910cfe724f3808496733/examples/mainwindow.py#L39-L40
